#!/usr/bin/env ruby

require "optparse"
require "s3_signed_url"

options = {}

OptionParser.new do |op|
  op.version = S3SignedUrl::VERSION
  op.banner = "Usage: s3_signed_url URL [--upload FILE]"

  op.on "-e", "--expire SECONDS", "The number of seconds before the presigned URL expires. Defaults: 900 (15 min)" do |v|
    options[:expire] = v
  end

  op.on "-u", "--upload FILE", "Upload the file for the URL" do |v|
    options[:upload] = v
  end

  op.on "-s", "--[no-]secure", "Use HTTPS or not. Default: true" do |v|
    options[:secure] = v
  end

  op.on "-m", "--method METHOD", "HTTP Method (GET|PUT). Default: GET" do |v|
    options[:method] = v
  end
end.parse!(ARGV)

url = ARGV[0]
puts S3SignedUrl::Cli.new(url, options).run
